#!/bin/bash

killer="detail: 127"  # Pause/Break

xinput test-xi2 --root 3 | grep -A2 --line-buffered "RawKeyPress" | grep --line-buffered "detail" | while read -r line; do
    if [[ $line == $killer ]]; then
        pkill chromium-browse
    fi
done
